### ISSUE TITLE
Is an SNS topic still required?

### ISSUE THREAD

**Issue by ghost** [pauld-splunk/aws-s3-sqs-lambda#1]
S3 can now forward notifications directly to SQS queues and even Lambda functions. As such, can we simplify this design to omit the SNS topic (and even the first SQS queue)?

**Comment by pauld-splunk** [comment]
Yes, you can get a notification directly to Lambda - however, the reasoning behind this first stage is that it protects against failures inside the Lambda function - e.g. you will not lose any notifications for example if you've updated the function and it crashes. Keeping the SNS vs going direct to SQS was a consistency decision with the current SQS-Based S3 input configuration, so that this could be "plugged into" existing configurations.
Both these of course can for sure be simplified if the above comments are not needed - this is an example of what is possible. :-)
